-- Adiciona valores ao enum CaseTimelineKind para Case Brain Refactor.
-- F1 (STRATEGY_GENERATED), F2 (BRAIN_GENERATED) e F4.5 (DOCUMENT_INCONSISTENCY).

ALTER TYPE "CaseTimelineKind" ADD VALUE IF NOT EXISTS 'STRATEGY_GENERATED';
ALTER TYPE "CaseTimelineKind" ADD VALUE IF NOT EXISTS 'BRAIN_GENERATED';
ALTER TYPE "CaseTimelineKind" ADD VALUE IF NOT EXISTS 'DOCUMENT_INCONSISTENCY';
